Models/Client.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AvaliacaoDeveloperMVC.Models
{
    public class Client
    {
        public int Id { get; set; } 
        public string Plate { get; set; }
        public string Renavam { get; set; }
        public string OwnerName { get; set; }
        public string OwnerCPF { get; set; }
        public bool isBlocked { get; set; }

    }
}

Controllers/ClientController.cs
using AvaliacaoDeveloperMVC.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AvaliacaoDeveloperMVC.Controllers
{
    public class ClientController : Controller
    {
        UnitOfWork.UnitOfWorkApp _uow;
        public ClientController()
        {
            _uow = new UnitOfWork.UnitOfWorkApp();
        }
        // GET: Client
        public ActionResult Index()
        {
            return View(_uow.ClientRepository.FindAll());
        }

        // GET: Client/Details/5
        public ActionResult Details(int id)
        {
            return View(_uow.ClientRepository.FindBy(id));
        }

        // GET: Client/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Client/Create
        [HttpPost]
        public ActionResult Create(Client client)
        {
            try
            {
                // TODO: Add insert logic here
                _uow.ClientRepository.Add(client);
                //foreach (HttpPostedFile postedFile in file.InputStream )
                //{
                //    string fileName = Path.GetFileName(postedFile.FileName);
                //    string fileExtention = Path.GetExtension(fileName);
                //    int fileSize = postedFile.ContentLength;

                //    if (fileExtention == ".jpg" || fileExtention == ".jpeg" || fileExtention == ".png")
                //    {

                //        postedFile.SaveAs(Server.MapPath("Upload/" + guid + "/" + fileName));

                //        //capturar a string de conexao
                //        System.Configuration.Configuration rootWebConfig = System.Web.Configuration.WebConfigurationManager.OpenWebConfiguration("/MyWebSiteRoot");
                //        System.Configuration.ConnectionStringSettings connString;
                //        connString = rootWebConfig.ConnectionStrings.ConnectionStrings["ConnectionString"];
                //        //cria um objeto de conexão
                //        SqlConnection con = new SqlConnection();
                //        con.ConnectionString = connString.ToString();
                //        SqlCommand cmd = new SqlCommand();
                //        cmd.Connection = con;
                //        cmd.CommandText = "AtualizarImageId";
                //        cmd.CommandType = CommandType.StoredProcedure;
                //        cmd.Parameters.AddWithValue("nome", fileName);
                //        //cmd.Parameters.AddWithValue("tamanho", fileSize);
                //        cmd.Parameters.AddWithValue("imagePath", "Upload/" + guid + "/" + fileName);
                //        cmd.Parameters.AddWithValue("Id", );

                //        con.Open();
                //        cmd.ExecuteNonQuery();
                //        con.Close();

                //        //lMsg.Text = "Os dados e imagens foram enviadas com sucesso";

                //    }
                //    else
                //    {
                //        throw new Exception("Formato " + fileExtention + " não é suportado");
                //    }
                //}



                _uow.Commit();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //public void Upload (HttpPostedFile file, string guid)
        //{
        //    try
        //    {
        //        if (file.ContentLength > 0)
        //        {
        //            string _FileName = Path.GetFileName(file.FileName);
        //            string _path = Path.Combine(Server.MapPath("~/Upload/" + guid + "/" + fileName"), _FileName);
        //            file.SaveAs(_path);
        //        }
        //        //ViewBag.Message = "File Uploaded Successfully!!";
        //        //return View();
        //    }
        //    catch
        //    {
        //        //ViewBag.Message = "File upload failed!!";
        //        //return View();
        //    }
        //}
    

        // GET: Client/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_uow.ClientRepository.FindBy(id));
        }

        // POST: Client/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Client client)
        {
            try
            {
                // TODO: Add update logic here
                _uow.ClientRepository.Edit(client);
                _uow.Commit();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Client/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_uow.ClientRepository.FindBy(id));
        }

        // POST: Client/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Client client)
        {
            try
            {
                // TODO: Add delete logic here
                _uow.ClientRepository.Remove(_uow.ClientRepository.FindBy(id));
                _uow.Commit();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Client/Create.cshtml
@model AvaliacaoDeveloperMVC.Models.Client

@{
    ViewBag.Title = "Create";
}

<h2>Cadastrar Veículo</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Client</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Plate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Plate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Plate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Renavam, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Renavam, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Renavam, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OwnerName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OwnerName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OwnerName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OwnerCPF, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OwnerCPF, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OwnerCPF, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        @Html.Label("Upload Image", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @using (Html.BeginForm("Create",
                                    "Client",
                                    FormMethod.Post,
                                    new { enctype = "multipart/form-data" }))
            {
                <label for="file">Upload Image:</label>
                <input type="file" name="file" id="file" multiple="multiple" />
                <br><br>

                <input type="submit" value="Upload Image" />
                <br><br>
                @ViewBag.Message
                <br>
            }
        </div>
    </div>*@

    @*<div class="form-group">
        <asp:FileUpload ID="FileUpload1" runat="server" multiple="multiple" />
    </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.isBlocked, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.isBlocked)
            @Html.ValidationMessageFor(model => model.isBlocked, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Client/Delete.cshtml
@model AvaliacaoDeveloperMVC.Models.Client

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Client</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Plate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Plate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Renavam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Renavam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnerCPF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerCPF)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isBlocked)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isBlocked)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Client/Details.cshtml
@model AvaliacaoDeveloperMVC.Models.Client

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Client</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Plate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Plate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Renavam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Renavam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnerCPF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerCPF)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isBlocked)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isBlocked)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Client/Edit.cshtml
@model AvaliacaoDeveloperMVC.Models.Client

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Client</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Plate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Plate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Plate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Renavam, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Renavam, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Renavam, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OwnerName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OwnerName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OwnerName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OwnerCPF, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OwnerCPF, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OwnerCPF, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.isBlocked, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.isBlocked)
            @Html.ValidationMessageFor(model => model.isBlocked, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Client/Index.cshtml
@model IEnumerable<AvaliacaoDeveloperMVC.Models.Client>

@{
    ViewBag.Title = "Lista de Veículos";
}

<h2>Lista de Veículos</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.isBlocked)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Plate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Renavam)
        </th>
        
        <th>Ações</th>
    </tr>

@foreach (var item in Model) {


<tr>
        <td>
            @if (item.isBlocked) {
                <img width="50" height="50" src="~/Pictures/lock2.png" />
            }
            else
            {
                <img width="50" height="50" src="~/Pictures/unlock2.png"/>
            }

        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Plate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Renavam)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>